Poller/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('polls.urls')),
    path('register/',user_views.register,name='register'),
    path('profile/<int:user_id>',user_views.profile,name='profile'),
    path('login/',auth_views.LoginView.as_view(template_name = 'users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'users/logout.html'),name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('',views.home,name='home'),
    path('polls/<int:poll_id>/',views.detail,name='detail'),
    path('polls/<int:poll_id>/results/',views.results,name='results'),
    path('polls/create/',views.create,name='create'),
    path('polls/search/',views.search,name='search'),
]

polls/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

def returnNone():
    no_users = User.objects.none()
    return no_users

class Poll(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    users_voted = models.ManyToManyField(User,related_name='usersvoted',default=returnNone)
    total_votes = models.IntegerField(default=0)
    no_of_options_to_be_selected = models.PositiveIntegerField(default=1)
    anonymous_poll = models.BooleanField(default=True)
    public_results = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    
class Choice(models.Model):
    parent_poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100,)
    vote_count = models.IntegerField(default=0)
    voted_by = models.ManyToManyField(User,default=returnNone)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django.shortcuts import get_object_or_404
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from .models import Poll

class PollForm(ModelForm):
    class Meta:
        model = Poll
        fields = ['title','description','no_of_options_to_be_selected','anonymous_poll','public_results']

class ChoiceFormSet(forms.BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super(ChoiceFormSet, self).__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = False

class SortForm(forms.Form):
    choices_tuple = [
        ('new','New'),
        ('old','Old'),
        ('top','Top'),
    ]

    sort_by = forms.ChoiceField(widget=forms.Select,choices=choices_tuple)

class SearchForm(forms.Form):
    
    anon_tuple = [
        ('any','Any'),
        ('anon','Anonymous'),
        ('nonon','Non-Anonymous'),
    ]
    results_tuple = [
        ('any','Any'),
        ('public','Public'),
        ('private','Private'),
    ]
    order_tuple = [
        ('new','New'),
        ('old','Old'),
        ('top','Top'),
    ]

    search = forms.CharField(required=False)
    search_sort_by = forms.ChoiceField(widget=forms.Select,choices=order_tuple)
    anonymity = forms.ChoiceField(widget=forms.Select,choices=anon_tuple)
    results_access = forms.ChoiceField(widget=forms.Select,choices=results_tuple)
        
def createVotingForm(poll_id):
    poll = get_object_or_404(Poll,pk=poll_id)
    choices_tuple = [(c.id,c.choice_text) for c in poll.choice_set.all()]

    class VotingForm(forms.Form):
        multiple_choice_field = forms.MultipleChoiceField(choices=choices_tuple,widget=forms.CheckboxSelectMultiple(attrs={'class':'check'}))

        def clean(self):
            
            cleaned_data = super().clean()

            if(cleaned_data.get('multiple_choice_field')):
                if len(cleaned_data.get('multiple_choice_field')) != poll.no_of_options_to_be_selected:
                    raise ValidationError(f"You have to choose exactly {poll.no_of_options_to_be_selected} options")

    return VotingForm

polls/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .models import Poll,Choice
from . import forms
from django.forms import modelformset_factory
from django.db.models import Q

def home(request):

    sortform = forms.SortForm(request.GET or None)
    sort_option = request.GET.get('sort_by')

    qs = None
    if sort_option == 'new' or sort_option == None:
        qs = Poll.objects.order_by('-date_posted')
    if sort_option == 'old':
        qs = Poll.objects.order_by('date_posted')
    elif sort_option == 'top':
        qs = Poll.objects.order_by('-total_votes')
    

    context = {
        'polls' : qs,
        'title' : 'Poller - Home',
        'sortform': sortform
    }

    return render(request,'polls/home.html',context)
    

def detail(request, poll_id):
    poll = get_object_or_404(Poll,pk=poll_id)

    if request.user in poll.users_voted.all():
        return HttpResponseRedirect(reverse('polls:results',args=[poll_id]))
    else:

        VotingForm = forms.createVotingForm(poll_id=poll_id)
        
        if request.method == 'POST':

            if not request.user.is_authenticated:
                return HttpResponseRedirect(reverse('login')+f"?next={request.path}")
                
            form = VotingForm(request.POST)
            
            if form.is_valid():
                selected_choices_id = form.cleaned_data.get('multiple_choice_field')
                selected_choices = []
                for choice_id in selected_choices_id:
                    selected_choices.append(poll.choice_set.get(id=choice_id))
                
                for selected_choice in selected_choices:
                    selected_choice.vote_count += 1
                    selected_choice.voted_by.add(request.user)
                    poll.total_votes +=1
                    selected_choice.save()

                poll.users_voted.add(request.user)
                poll.save()
            
                return redirect('polls:results',poll_id=poll_id)

        else:
            form = VotingForm()

        return render(request,'polls/detail.html',{'form':form,'choices':form.fields['multiple_choice_field'].choices , 'poll':poll ,'title':f"Poll no: {poll_id}"})
    


def results(request, poll_id):

    poll = get_object_or_404(Poll,pk=poll_id)
    perc_choice_pairs = [(round((choice.vote_count / poll.total_votes) * 100),choice) for choice in poll.choice_set.all()]

    if request.user in poll.users_voted.all():
        if poll.public_results == True:
            context = {
                'poll':poll,
                'pairs':perc_choice_pairs,
            }
        else:
            if request.user == poll.author:
                context = {
                'poll':poll,
                'pairs':perc_choice_pairs,
            }
            else:
                context = {
                    'poll': None,
                }

        return render(request,'polls/results.html',context)
    else:
        return redirect('polls:detail',poll_id=poll_id)

def create(request):
    ChoiceFormSet = modelformset_factory(Choice,fields=('choice_text',),extra=0,min_num=2,formset=forms.ChoiceFormSet,validate_min=True)
    qs = Choice.objects.none()

    if request.method == 'POST':

        choiceformset = ChoiceFormSet(request.POST)
        pollform = forms.PollForm(request.POST)

        if choiceformset.is_valid() and pollform.is_valid():
            parentpoll = pollform.save(commit=False)
            parentpoll.author = request.user
            parentpoll.save()

            choices = choiceformset.save(commit=False)

            for choice in choices:
                choice.parent_poll = parentpoll
                choice.save()
                
            messages.success(request,'Poll created successfully')
            return redirect(reverse('polls:detail',args=[parentpoll.id]))
        
    else:
        choiceformset = ChoiceFormSet(queryset=qs)
        pollform = forms.PollForm()

    context = {
        'choiceformset':choiceformset,
        'pollform':pollform,
    }
    
    for error in choiceformset.non_form_errors():
        print(error)

    return render(request,'polls/create.html',context)

def search(request):

    search = request.GET.get('search')
    sort = request.GET.get('sort_by')
    anon = request.GET.get('anonymity')
    results = request.GET.get('results_access')

    qs = Poll.objects.all()

    if anon == 'anon':
        qs = Poll.objects.filter(anonymous_poll=True)
    elif anon == 'nonon':
        qs = Poll.objects.filter(anonymous_poll=False)

    if results == 'public':
        qs = qs.filter(public_results=True)
    elif results == 'private':
        qs = qs.filter(public_results=False)

    qs = qs.filter(Q(description__contains=search) | Q(title__contains=search))

    if sort == 'new':
        qs = qs.order_by('-date_posted')
    elif sort == 'old':
        qs = qs.order_by('date_posted')
    elif sort == 'top':
        qs = qs.order_by('-total_votes')

    context = {
        'polls':qs
    }

    print(qs)

    return render(request,'polls/search.html',context)

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Poller</title>
    {% endif %}

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-expand-xl navbar-dark bg-dark sticky-top px-5 shadow-sm" style="min-height: 8%;">
        <div class="container-fluid">

          <a class="navbar-brand mx-4" href="{% url 'polls:home' %}">Poller</a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item me-3">
                <a class="nav-link active" aria-current="page" href="{% url 'polls:home' %}">Home</a>
              </li>
            </ul>

            <form action="{% url 'polls:search' %}" method="get">
              <div class="btn-group">

                <input type="text" name="search" id="id_search" placeholder="Search" class="form-control" style="border-top-right-radius: 0; border-bottom-right-radius: 0;">
                <button type="button" class="btn-secondary btn dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                  <span class="visually-hidden">Toggle Dropdown</span>
                </button>

                <ul class="dropdown-menu shadow-lg border border-dark">
                  <div class="p-2">
                    <div class="mt-3">
                      <label for="id_sort_by">Sort by:</label>
                      <select name="search_sort_by" id="search_sort_by">
                        <option value="new">New</option>
                        <option value="old">Old</option>
                        <option value="top">Top</option>
                      </select>
                    </div>
                    
                    <div class="mt-3">
                    <label for="id_anonymity">Anonymity:</label>
                    <select name="anonymity" id="id_anonymity">
                        <option value="any">Any</option>
                        <option value="anon">Anonymous</option>
                        <option value="nonon">Non-Anonymous</option>
                    </select>
                    </div>
                    
                    <div class="mt-3">
                    <label for="id_results_access">Results access:</label>
                    <select name="results_access" id="id_results_access">
                        <option value="any">Any</option>
                        <option value="public">Public</option>
                        <option value="private">Private</option>
                    </select>
                    </div>
            
                    <div class="d-flex justify-content-end mt-3">
                    <button type="submit" class="btn btn-outline-success" for>Search</button>
                    </div>
                  </div>
                </ul>
              </div>
            </form>

            <ul class="navbar-nav ms-2 mb-2 mb-lg-0 align-items-center">
              {% if request.user.is_authenticated %}
              <li class="nav-item mx-2">
                <a class="nav-link active" aria-current="page" href="{% url 'polls:create' %}">New Poll</a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link active" aria-current="page" href="{% url 'profile' user.id %}">Profile</a>
              </li>
              <li class="nav-item">
                <div class="d-flex align-items-center justify-content-center">  
                  <img src="{{ user.profile.image.url }}" align="middle" class="rounded-circle pfp-lil">
                </div>
              </li>
              
              {% else %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'login' %}?next={{ request.path }}">Login</a>
              </li>
              <li class="nav-item me-2">
                <a class="nav-link active" aria-current="page" href="{% url 'register' %}">Register</a>
              </li>
              {% endif %}
            </ul>

          </div>
        </div>
    </nav>
    {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} mb-0" role="alert">
        {{ message }}
      </div>      
      {% endfor %}
    {% endif %}

    <div class="main-flex">
      <div class="flex-left">
        
      </div>
      <div class="flex-center px-5 border-start border-end shadow-sm" >
        {% block content %}
        {% endblock content %}
      </div>
      <div class="flex-right">
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
</body>
</html>

polls/templates/polls/create.html
{% extends 'polls/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post">

        {% csrf_token %}

        {{ pollform | crispy}}
        {{ choiceformset.management_form }}

        <button id="add-choice" type="button" class="btn btn-light mt-3 border border-dark rounded">Add Choice</button>
        <button id="del-choice" type="button" class="btn btn-danger mt-3 border border-dark rounded">Del Choice</button>

        <div id="choice-form-list">
            <div class="mt-2">
                <ul class="mb-0">
                    {% for error in choiceformset.non_form_errors %}
                    <li class="fw-semibold text-danger mb-0">{{ error }}</li>
                    {% endfor %}
                    
                </ul>
                
            </div>
            {% for choiceform in choiceformset %}
                <div class="choice-form">
                    {{ choiceform | crispy}}
                </div>
            {% endfor %}
        </div>
        
        <div id="empty-form" class="hidden">{{ choiceformset.empty_form | crispy }}</div>
        
        <button type="submit" class="btn btn-outline-success my-3">Submit Poll</button>
    </form>

    <script>
        document.getElementById('id_no_of_options_to_be_selected').setAttribute('min',1)
        document.getElementById('id_no_of_options_to_be_selected').setAttribute('max',2)


        const addChoiceButton = document.getElementById('add-choice')
        const deleteChoiceButton = document.getElementById('del-choice')

        const totalForms = document.getElementById('id_form-TOTAL_FORMS')

        addChoiceButton.addEventListener('click',add_choice_form)
        deleteChoiceButton.addEventListener('click',del_choice_form)
        
        function add_choice_form(args){

            if(event){
                event.preventDefault()
            }

            const currentChoiceForms = document.getElementsByClassName('choice-form')
            let currentChoiceFormCount = currentChoiceForms.length

            const formCopyTarget = document.getElementById('choice-form-list')
            const emptyFormEl = document.getElementById('empty-form').cloneNode(true)

            emptyFormEl.setAttribute('class','choice-form')
            emptyFormEl.setAttribute('id',`form-${currentChoiceFormCount}`)

            const regex = new RegExp('__prefix__','g')
            emptyFormEl.innerHTML = emptyFormEl.innerHTML.replace(regex,currentChoiceFormCount)
            
            totalForms.setAttribute('value',currentChoiceFormCount+1)
            document.getElementById('id_no_of_options_to_be_selected').setAttribute('max',currentChoiceFormCount+1)

            formCopyTarget.append(emptyFormEl)

        }

        function del_choice_form(args){

            if(event){
                event.preventDefault()
            }

            const currentChoiceForms = document.getElementsByClassName('choice-form')
            let currentChoiceFormCount = currentChoiceForms.length

            if (currentChoiceFormCount == 2){
                alert('You need atleast 2 options in your poll')
            }
            else{
                // Delete form
                const lastChoiceForm = currentChoiceForms[currentChoiceFormCount-1]
                lastChoiceForm.remove()
                
                totalForms.setAttribute('value',currentChoiceFormCount-1)
                document.getElementById('id_no_of_options_to_be_selected').setAttribute('max',currentChoiceFormCount-1)

                formCopyTarget.append(emptyFormEl)
            }
            

        }

    </script>

{% endblock content %}

polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="mt-5 p-5 mx-auto border border-dark rounded">
    <div class="row mt-2 ps-3">
        <div class="d-flex align-items-center">
            <div class="flex-grow-1">
                <div class="">
                    <h1 class="d-inline-block">{{ poll.title }}</h1>
    
                    {% if poll.anonymous_poll %}
                    <span class="badge text-bg-success">Anonymous</span>
                    {% else %}
                    <span class="badge text-bg-danger">Non-Anonymous</span>
                    {% endif %}

                    {% if poll.public_results %}
                    <span class="badge text-bg-primary">Public Results</span>
                    {% else %}
                    <span class="badge text-bg-secondary">Private Results</span>
                    {% endif %}
                </div>  
            </div>
            <div class="mx-1">
                <a href="{% url 'profile' poll.author.id %}">{{ poll.author }}</a>
            </div>
            <div class="mx-1 my-1">
                <img src="{{ poll.author.profile.image.url }}" align="middle" class="rounded-circle pfp-sm">
            </div>
        </div>
    </div>
    <div class="ps-3">
        <span class="fw-light fst-italic">On {{ poll.date_posted }}</span>
        {% if poll.votes == 1 %}
            <span class="fw-semibold">1 Vote</span>  
        {% else %}
            <span class="fw-semibold ms-2">{{ poll.total_votes }} Votes</span>  
        {% endif %}
    </div>

    <div class="d-flex ps-3 my-2 align-items-end justify-content-end">
        {% if poll.description %}
            <div class="bg-light border rounded px-3 py-2 flex-grow-1">
                <div class="wrap d-inline-block">
                    {{ poll.description }}
                </div>
            </div>
        {% endif %}
        <div class="alert alert-info font-info py-1 mb-0 mx-3 d-inline-block flex-shrink-0">
            Select exactly {{ poll.no_of_options_to_be_selected }} options
        </div>
    </div>

    <div class="row">
        <form action="{% url 'polls:detail' poll.id %}" method="post" class="">
            {% csrf_token %}
            
            {% if form.non_field_errors %}
                <div class="alert alert-danger font-info pe-2 pt-0 ps-0 pb-0 ms-3 mt-0 mb-2 d-inline-block text-center">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            

            {% for field in form %}
            <div class="fieldWrapper">

                {% if field.errors %}
                    <div class="alert alert-danger font-info pe-2 pt-0 ps-0 pb-0 ms-3 mt-0 mb-2 d-inline-block text-center">
                        {{ field.errors }}
                    </div>
                {% endif %}
                

                {% for val,text in choices %}
                <div>                    
                    <input type="checkbox" name="multiple_choice_field" id="checkbox-{{ val }}" class="check" value="{{ val }}">
                    <label class="chkbox-label wrap w-95 d-inline-block form-check-label" for="checkbox-{{ val }}">{{ text }}</label>
                </div>
                {% endfor %}

                {% if field.help_text %}
                <p class="help">{{ field.help_text | safe }}</p>
                {% endif %}

            </div>
            {% endfor %}

            <button class="btn btn-outline-success "type="submit">Submit</button>

        </form>
    </div>
</div>




<script>
    var checks = document.querySelectorAll(".check");
    var max = {{ poll.no_of_options_to_be_selected }};

    for (var i = 0; i < checks.length; i++)
        checks[i].onclick = selectiveCheck;

    function selectiveCheck(event) {
        var checkedChecks = document.querySelectorAll(".check:checked");
        if (checkedChecks.length >= max + 1)
            return false;
    };

</script>
{% endblock content %}

polls/templates/polls/home.html
{% extends "polls/base.html" %}
{% block content %}

    <h1 class="border-bottom mt-4 pb-1">Home</h1>
    {% if polls %}
    <form method="get" id="sort-form" class="mt-3">
        
        {{ sortform.non_field_errors }}

        {% for field in sortform %}
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
        {% endfor %}
        
    </form>
    
    {% for poll in polls %}
        <div class="card my-3">
            <div class="card-body ps-4">
                <div class="d-flex">
                    <div class="d-flex align-items-center justify-content-center">  
                        <img src="{{ poll.author.profile.image.url }}" align="middle" class="rounded-circle pfp-sm">
                    </div>
                    <div class="ms-3 flex-grow-1">
                        <h3 class="card-title">{{ poll.title }}</a></h3>
                        <h6 class="card-subtitle mb-2 text-muted">By {{ poll.author }} on {{ poll.date_posted }}</h6>
                    </div>      
                    <div class="">
                        <div class="d-flex flex-column align-items-center">
                            <div class="flex-grow-1">
                                {% if poll.anonymous_poll %}
                                <span class="badge text-bg-success">Anonymous</span>
                                {% else %}
                                <span class="badge text-bg-danger">Non-Anonymous</span>
                                {% endif %}
                            </div>
                            <div class="flex-grow-1">
                                {% if poll.public_results %}
                                <span class="badge text-bg-primary">Public Results</span>
                                {% else %}
                                <span class="badge text-bg-secondary">Private Results</span>
                                {% endif %}
                            </div>
                            
                            
                        </div>
                        
                    </div>
                </div>
                <div class="d-flex mt-2">
                    <div class="flex-grow-1">
                        <button class="btn btn-sm btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#details-{{ poll.id }}" aria-expanded="false" aria-controls="details-{{ poll.id }}">Details</button>
                        <a class="btn btn-sm btn-primary" href="{% url 'polls:detail' poll.id %}">Visit</a>
                    </div>
                    <div class="ps-3">
                        {% if poll.votes == 1 %}
                            <span class="fw-semibold">1 Vote</span>  
                        {% else %}
                            <span class="fw-semibold ms-2">{{ poll.total_votes }} Votes</span>  
                        {% endif %}
                    </div>
                </div>

                <div class="collapse mt-2" id="details-{{ poll.id }}">
                    <div class="d-flex card card-body bg-light">
                        <div class="mb-2 ms-2">
                            {{ poll.description }}
                        </div>
                        <div class="flex-grow-0">
                            <ul class="list-group">
                                {% for choice in poll.choice_set.all %}
                                    <li class="list-group-item wrap">{{ choice.choice_text }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    
                    
                </div>
            </div>
        </div>
    {% endfor %}


    
    {% else %}
        <p>No polls available right now</p>
    {% endif %}

    <script>
        $('#id_sort_by').change(function(){
            $('#sort-form').submit()
        })
    </script>

{% endblock content %}

polls/templates/polls/search.html
{% extends "polls/base.html" %}
{% block content %}
<h1 class="border-bottom mt-3 pb-1">Results for : '{{ request.GET.search }}'</h1>
    {% if polls %}
        {% for poll in polls %}
            <div class="card my-3">
                <div class="card-body ps-4">
                    <div class="d-flex">
                        <div class="d-flex align-items-center justify-content-center">  
                            <img src="{{ poll.author.profile.image.url }}" align="middle" class="rounded-circle pfp-sm">
                        </div>
                        <div class="ms-3 flex-grow-1">
                            <h3 class="card-title">{{ poll.title }}</a></h3>
                            <h6 class="card-subtitle mb-2 text-muted">By {{ poll.author }} on {{ poll.date_posted }}</h6>
                        </div>      
                        <div class="">
                            <div class="d-flex flex-column align-items-center">
                                <div class="flex-grow-1">
                                    {% if poll.anonymous_poll %}
                                    <span class="badge text-bg-success">Anonymous</span>
                                    {% else %}
                                    <span class="badge text-bg-danger">Non-Anonymous</span>
                                    {% endif %}
                                </div>
                                <div class="flex-grow-1">
                                    {% if poll.public_results %}
                                    <span class="badge text-bg-primary">Public Results</span>
                                    {% else %}
                                    <span class="badge text-bg-secondary">Private Results</span>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex mt-2">
                        <div class="flex-grow-1">
                            <button class="btn btn-sm btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#details-{{ poll.id }}" aria-expanded="false" aria-controls="details-{{ poll.id }}">Details</button>
                            <a class="btn btn-sm btn-primary" href="{% url 'polls:detail' poll.id %}">Visit</a>
                        </div>
                        <div class="ps-3">
                            {% if poll.votes == 1 %}
                                <span class="fw-semibold">1 Vote</span>  
                            {% else %}
                                <span class="fw-semibold ms-2">{{ poll.total_votes }} Votes</span>  
                            {% endif %}
                        </div>
                    </div>

                    <div class="collapse mt-2" id="details-{{ poll.id }}">
                        <div class="d-flex card card-body bg-light">
                            <div class="mb-2 ms-2">
                                {{ poll.description }}
                            </div>
                            <div class="flex-grow-0">
                                <ul class="list-group">
                                    {% for choice in poll.choice_set.all %}
                                        <li class="list-group-item wrap">{{ choice.choice_text }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h1 class="display-4 text-center">No polls found!</h1>
    {% endif %}

    <script>
        $('#id_sort_by').change(function(){
            $('#sort-form').submit()
        })
    </script>

{% endblock content %}