Poller/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('polls.urls')),
    path('register/',user_views.register,name='register'),
    path('profile/<int:user_id>',user_views.profile,name='profile'),
    path('login/',auth_views.LoginView.as_view(template_name = 'users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'users/logout.html'),name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('',views.home,name='home'),
    path('polls/<int:poll_id>/',views.detail,name='detail'),
    path('polls/<int:poll_id>/results/',views.results,name='results'),
    path('polls/create/',views.create,name='create'),
    path('polls/search/',views.search,name='search'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='default_pfp.jpeg', upload_to='profile_pics')

    def __str__(self):
        return f"{self.user.username} Profile"

    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

polls/forms.py
from django.shortcuts import get_object_or_404
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from .models import Poll

class PollForm(ModelForm):
    class Meta:
        model = Poll
        fields = ['title','description','no_of_options_to_be_selected','anonymous_poll','public_results']

class ChoiceFormSet(forms.BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super(ChoiceFormSet, self).__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = False

class SortForm(forms.Form):
    choices_tuple = [
        ('new','New'),
        ('old','Old'),
        ('top','Top'),
    ]

    sort_by = forms.ChoiceField(widget=forms.Select,choices=choices_tuple)

class SearchForm(forms.Form):
    
    anon_tuple = [
        ('any','Any'),
        ('anon','Anonymous'),
        ('nonon','Non-Anonymous'),
    ]
    results_tuple = [
        ('any','Any'),
        ('public','Public'),
        ('private','Private'),
    ]
    order_tuple = [
        ('new','New'),
        ('old','Old'),
        ('top','Top'),
    ]

    search = forms.CharField(required=False)
    search_sort_by = forms.ChoiceField(widget=forms.Select,choices=order_tuple)
    anonymity = forms.ChoiceField(widget=forms.Select,choices=anon_tuple)
    results_access = forms.ChoiceField(widget=forms.Select,choices=results_tuple)
        
def createVotingForm(poll_id):
    poll = get_object_or_404(Poll,pk=poll_id)
    choices_tuple = [(c.id,c.choice_text) for c in poll.choice_set.all()]

    class VotingForm(forms.Form):
        multiple_choice_field = forms.MultipleChoiceField(choices=choices_tuple,widget=forms.CheckboxSelectMultiple(attrs={'class':'check'}))

        def clean(self):
            
            cleaned_data = super().clean()

            if(cleaned_data.get('multiple_choice_field')):
                if len(cleaned_data.get('multiple_choice_field')) != poll.no_of_options_to_be_selected:
                    raise ValidationError(f"You have to choose exactly {poll.no_of_options_to_be_selected} options")

    return VotingForm

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    # first_name = forms.TextInput()
    # last_name = forms.TextInput()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class UserUpdateForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ['username','email']


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['image']

users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from .forms import UserRegisterForm,UserUpdateForm,ProfileUpdateForm
from polls.forms import SortForm
from polls.models import Poll

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get('username')
            new_user = authenticate(username = form.cleaned_data['username'],password=form.cleaned_data['password1'],)
            login(request,new_user)
            messages.success(request,f'Account Created for {username}!')
            return redirect('polls:home')
    else:
        form = UserRegisterForm()

    return render(request,'users/register.html',{'form':form})


def profile(request,user_id):
    
    requested_user = get_object_or_404(User,id=user_id)

    sortform = SortForm(request.GET or None)
    sort_option = request.GET.get('sort_by')

    qs = None
    if sort_option == 'new' or sort_option == None:
        qs = requested_user.poll_set.order_by('-date_posted')
    if sort_option == 'old':
        qs = requested_user.poll_set.order_by('date_posted')
    elif sort_option == 'top':
        qs = requested_user.poll_set.order_by('-total_votes')

    if request.user == requested_user and request.user.is_authenticated:
        if request.method == 'POST':
            uform = UserUpdateForm(request.POST,instance=request.user)
            pform = ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)

            if uform.is_valid() and pform.is_valid():
                uform.save()
                pform.save()
                messages.success(request,f'Account updates successfully!')
                return redirect('profile',user_id = request.user.id)
        else:
            uform = UserUpdateForm(instance=request.user)
            pform = ProfileUpdateForm(instance=request.user)

        context = {
            'u_form':uform,
            'p_form':pform,
            'user':requested_user,
            'allow_edit':True,
            'polls':qs,
            'sortform':sortform,
        }
    else:

        context = {'user':requested_user,'allow_edit':False,'polls':qs,'sortform':sortform,}


    return render(request,'users/profile.html',context)

users/templates/users/login.html
{% extends "polls/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="border-bottom pb-2 my-3">Login</h1>
  <form method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit", class="btn btn-outline-primary mt-2">Sign In</button>
  </form>
  <p class="text-muted text-center">Need an account? <a href="{% url 'register' %}">Register</a> Now! </p>
{% endblock content %}

users/templates/users/logout.html
{% extends "polls/base.html" %}
{% block content %}
  <h2 class="mt-5 fw-semibold border-bottom pb-2">Logged out succesfully!</h2>
  <p class="text-muted text-center mt-2"><a href="{% url 'login' %}">Login Again</a></p>
{% endblock content %}

users/templates/users/profile.html
{% extends "polls/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<h1 class="display-4 mt-5 pb-2 border-bottom">Profile info</h1>

<div class="mt-3 border border-dark rounded">
    <div class="d-flex align-items-start px-4 py-3">
        <div>
            <h2 class="">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
        <div class="ms-auto">
            <img class="pfp" src="{{ user.profile.image.url }}">
        </div>

    </div>
</div>

{% if allow_edit %}
<h1 class="display-4 mt-5 pb-2 border-bottom">Edit Profile</h1>
<form method="POST" enctype="multipart/form-data" class="border border-dark rounded px-4 py-3 mt-3">
    {% csrf_token %}
    {{ u_form | crispy }}
    {{ p_form | crispy }}
    <button class="btn btn-outline-primary mt-2" type="submit">Update</button>
</form>
{% endif %}

<h1 class="display-4 mt-5 pb-2 border-bottom">User's Polls</h1>
<div class="my-3 border border-dark rounded px-4 py-3 mt-3">
    <form method="get" id="sort-form" class="mt-3">
        
        {{ sortform.non_field_errors }}

        {% for field in sortform %}
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
        {% endfor %}
        
    </form>

    {% if polls %}
        {% for poll in polls %}
        <div class="card my-3">
            <div class="card-body ps-4">
                
                <div class="d-flex">
                    <div class="d-flex align-items-center justify-content-center">
                        <img src="{{ poll.author.profile.image.url }}" align="middle" class="rounded-circle pfp-sm">
                    </div>
                    <div class="ms-3 flex-grow-1">
                        <h3 class="card-title">{{ poll.title }}</a></h3>
                        <h6 class="card-subtitle mb-2 text-muted">By {{ poll.author }} on {{ poll.date_posted }}</h6>
                    </div>
                    <div class="">
                        <div class="d-flex flex-column align-items-center">
                            <div class="flex-grow-1">
                                {% if poll.anonymous_poll %}
                                <span class="badge text-bg-success">Anonymous</span>
                                {% else %}
                                <span class="badge text-bg-danger">Non-Anonymous</span>
                                {% endif %}
                            </div>
                            <div class="flex-grow-1">
                                {% if poll.public_results %}
                                <span class="badge text-bg-primary">Public Results</span>
                                {% else %}
                                <span class="badge text-bg-secondary">Private Results</span>
                                {% endif %}
                            </div>
                        </div>

                    </div>
                </div>

                <div class="d-flex mt-2">
                    <div class="flex-grow-1">
                        <button class="btn btn-sm btn-secondary" type="button" data-bs-toggle="collapse"
                            data-bs-target="#details-{{ poll.id }}" aria-expanded="false"
                            aria-controls="details-{{ poll.id }}">Details</button>
                        <a class="btn btn-sm btn-primary" href="{% url 'polls:detail' poll.id %}">Visit</a>
                    </div>
                    <div class="ps-3">
                        {% if poll.votes == 1 %}
                        <span class="fw-semibold">1 Vote</span>
                        {% else %}
                        <span class="fw-semibold ms-2">{{ poll.total_votes }} Votes</span>
                        {% endif %}
                    </div>
                </div>

                <div class="collapse mt-2" id="details-{{ poll.id }}">
                    <div class="d-flex card card-body bg-light">
                        <div class="mb-2 ms-2">
                            {{ poll.description }}
                        </div>
                        <div>
                            <ul class="list-group">
                                {% for choice in poll.choice_set.all %}
                                <li class="list-group-item">{{ choice.choice_text }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <h6 class="text-center fw-semibold">This user has no Polls.</h6>
    {% endif %}
</div>

<script>
    $('#id_sort_by').change(function(){
        $('#sort-form').submit()
    })
</script>

{% endblock content %}

users/templates/users/register.html
{% extends "polls/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <h1 class="border-bottom pb-2 my-3">Sign up</h1>
  <form method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit", class="btn btn-outline-primary mt-2">Sign up</button>
  </form>
  <p class="text-muted text-center">Already have an account? <a href="{% url 'register' %}">Login</a> Now! </p>
{% endblock content %}